#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
prospero-prx-fix-hash

Fix/check the SysV ELF .hash table of SCE/Prospero PRX/SPRX files after
renaming exported NID symbols.

Observed PRX detail:
    The dynamic symbol string is stored as:
        <11-char-NID>#<library-id-char>#<module-id-char>

    For exported symbols, the SysV .hash bucket is calculated from:
        <11-char-NID>#<real-export-library-name>#<real-module-name>

    The real names are stored in SCE .dynamic entries:
        DT_SCE_MODULE_INFO 0x61000043  -> current module name, module id 0 ('A')
        DT_SCE_EXPORT_LIB  0x61000047  -> export library name, id in d_val >> 48

This tool only changes the .hash section. It does not rename NIDs and it does
not touch .dynstr. Unknown non-export/import symbols are preserved in their
current buckets by default because their canonical-name rule is not the same as
exports in official PRX files.

Typical SDK installation:
    install -m755 prospero-prx-fix-hash /opt/ps5-payload-sdk/bin/

Examples:
    prospero-prx-fix-hash --check libSceAppContent.prx
    prospero-prx-fix-hash libSceAppContent_edited.prx libSceAppContent_fixed.prx
    prospero-prx-fix-hash --in-place --backup libSceAppContent_edited.prx
    prospero-prx-fix-hash --list libSceAppContent.prx
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import struct
import sys
from dataclasses import dataclass
from pathlib import Path

SCE_NID_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+-"
PRX_SYM_RE = re.compile(r"^([A-Za-z0-9+\-]{11})#([^#])#([^#])$")

# ELF constants.
DT_NULL = 0

# SCE/Prospero dynamic tags observed in PRX files generated by prospero-lld.
DT_SCE_MODULE_INFO = 0x61000043
DT_SCE_EXPORT_LIB = 0x61000047


class PrxHashError(Exception):
    pass


def id_char(n: int) -> str:
    if 0 <= n < len(SCE_NID_ALPHABET):
        return SCE_NID_ALPHABET[n]
    return f"?{n}?"


def id_num(ch: str) -> int:
    try:
        return SCE_NID_ALPHABET.index(ch)
    except ValueError:
        raise PrxHashError(f"bad PRX id char {ch!r}; expected one of {SCE_NID_ALPHABET!r}") from None


def sysv_elf_hash(name: str | bytes) -> int:
    """Classic SysV ELF hash used by the .hash bucket table."""
    data = name.encode("utf-8") if isinstance(name, str) else name
    h = 0
    for c in data:
        h = ((h << 4) + c) & 0xFFFFFFFF
        h ^= (h >> 24) & 0xF0
    return h & 0x0FFFFFFF


@dataclass(frozen=True)
class Section:
    index: int
    name: str
    name_off: int
    type: int
    flags: int
    addr: int
    offset: int
    size: int
    link: int
    info: int
    addralign: int
    entsize: int


@dataclass(frozen=True)
class DynSym:
    index: int
    name: str
    st_name: int
    st_info: int
    st_other: int
    st_shndx: int
    st_value: int
    st_size: int

    @property
    def prx_parts(self) -> tuple[str, str, str] | None:
        m = PRX_SYM_RE.match(self.name)
        if not m:
            return None
        return m.group(1), m.group(2), m.group(3)


@dataclass(frozen=True)
class ExportGroup:
    lib_id: int
    mod_id: int
    library: str
    module: str

    @property
    def lib_char(self) -> str:
        return id_char(self.lib_id)

    @property
    def mod_char(self) -> str:
        return id_char(self.mod_id)

    @property
    def suffix(self) -> str:
        return f"#{self.lib_char}#{self.mod_char}"

    def canonical(self, nid: str) -> str:
        return f"{nid}#{self.library}#{self.module}"


@dataclass
class AuditResult:
    path: Path
    nbucket: int
    nchain: int
    hash_offset: int
    export_ok: int
    export_bad: int
    export_total: int
    prx_non_export: int
    regular_symbols: int
    missing_bucket: int
    bad_lines: list[str]

    @property
    def ok(self) -> bool:
        return self.export_bad == 0 and self.missing_bucket == 0


class Elf64LE:
    def __init__(self, data: bytes):
        self.data = data
        if len(data) < 0x40:
            raise PrxHashError("file too small for an ELF64 header")
        if data[:4] != b"\x7fELF":
            raise PrxHashError("not an ELF file")
        if data[4] != 2:
            raise PrxHashError("expected ELFCLASS64")
        if data[5] != 1:
            raise PrxHashError("expected little-endian ELF")

        self.e_shoff = struct.unpack_from("<Q", data, 0x28)[0]
        self.e_shentsize = struct.unpack_from("<H", data, 0x3A)[0]
        self.e_shnum = struct.unpack_from("<H", data, 0x3C)[0]
        self.e_shstrndx = struct.unpack_from("<H", data, 0x3E)[0]
        if self.e_shentsize < 64:
            raise PrxHashError(f"unexpected section header size: {self.e_shentsize}")
        if self.e_shoff + self.e_shnum * self.e_shentsize > len(data):
            raise PrxHashError("section header table points outside the file")
        if not (0 <= self.e_shstrndx < self.e_shnum):
            raise PrxHashError("bad e_shstrndx")

        raw_sections = []
        for i in range(self.e_shnum):
            off = self.e_shoff + i * self.e_shentsize
            raw_sections.append(struct.unpack_from("<IIQQQQIIQQ", data, off))

        shstr_raw = raw_sections[self.e_shstrndx]
        shstr_off, shstr_size = shstr_raw[4], shstr_raw[5]
        if shstr_off + shstr_size > len(data):
            raise PrxHashError("section-name string table points outside the file")
        shstr = data[shstr_off:shstr_off + shstr_size]

        self.sections: list[Section] = []
        for i, sh in enumerate(raw_sections):
            name_off = sh[0]
            end = shstr.find(b"\0", name_off) if name_off < len(shstr) else -1
            name = shstr[name_off:end].decode("utf-8", "replace") if end >= 0 else ""
            self.sections.append(Section(i, name, *sh))

    def section(self, name: str) -> Section:
        for sh in self.sections:
            if sh.name == name:
                return sh
        raise PrxHashError(f"required section not found: {name}")

    def section_or_none(self, name: str) -> Section | None:
        for sh in self.sections:
            if sh.name == name:
                return sh
        return None

    def str_at(self, strtab: Section, off: int) -> str:
        start = strtab.offset + off
        if not (strtab.offset <= start < strtab.offset + strtab.size):
            raise PrxHashError(f"string offset 0x{off:x} outside {strtab.name}")
        end = self.data.find(b"\0", start, strtab.offset + strtab.size)
        if end < 0:
            raise PrxHashError(f"unterminated string at {strtab.name}+0x{off:x}")
        return self.data[start:end].decode("utf-8", "replace")

    def dynsyms(self) -> list[DynSym]:
        dynsym = self.section(".dynsym")
        dynstr = self.section(".dynstr")
        if dynsym.entsize < 24:
            raise PrxHashError(f"unexpected .dynsym entsize: {dynsym.entsize}")
        count = dynsym.size // dynsym.entsize
        out: list[DynSym] = []
        for i in range(count):
            off = dynsym.offset + i * dynsym.entsize
            st_name, st_info, st_other, st_shndx, st_value, st_size = struct.unpack_from("<IBBHQQ", self.data, off)
            name = ""
            if st_name:
                name = self.str_at(dynstr, st_name)
            out.append(DynSym(i, name, st_name, st_info, st_other, st_shndx, st_value, st_size))
        return out

    def dynamic_entries(self) -> list[tuple[int, int]]:
        dyn = self.section(".dynamic")
        if dyn.entsize < 16:
            raise PrxHashError(f"unexpected .dynamic entsize: {dyn.entsize}")
        count = dyn.size // dyn.entsize
        out: list[tuple[int, int]] = []
        for i in range(count):
            tag, val = struct.unpack_from("<QQ", self.data, dyn.offset + i * dyn.entsize)
            out.append((tag, val))
            if tag == DT_NULL:
                break
        return out

    def export_groups(self) -> dict[tuple[int, int], ExportGroup]:
        dynstr = self.section(".dynstr")
        library_by_id: dict[int, str] = {}
        module_by_id: dict[int, str] = {}

        for tag, val in self.dynamic_entries():
            name_off = val & 0xFFFFFFFF
            if tag == DT_SCE_MODULE_INFO:
                # In observed PRX files, the current module is encoded as id 0 => 'A'.
                module_by_id[0] = self.str_at(dynstr, name_off)
            elif tag == DT_SCE_EXPORT_LIB:
                lib_id = (val >> 48) & 0xFFFF
                library_by_id[lib_id] = self.str_at(dynstr, name_off)

        groups: dict[tuple[int, int], ExportGroup] = {}
        for lib_id, library in library_by_id.items():
            for mod_id, module in module_by_id.items():
                groups[(lib_id, mod_id)] = ExportGroup(lib_id, mod_id, library, module)
        return groups

    def hash_table(self) -> tuple[Section, int, int, list[int], list[int]]:
        sh = self.section(".hash")
        if sh.size < 8 or sh.size % 4:
            raise PrxHashError("bad .hash section size")
        words = list(struct.unpack_from(f"<{sh.size // 4}I", self.data, sh.offset))
        nbucket, nchain = words[0], words[1]
        need = 2 + nbucket + nchain
        if need > len(words):
            raise PrxHashError(".hash section is truncated")
        if nbucket == 0 or nchain == 0:
            raise PrxHashError(".hash has zero nbucket or nchain")
        return sh, nbucket, nchain, words[2:2 + nbucket], words[2 + nbucket:need]


def buckets_to_symbol_bucket_map(buckets: list[int], chains: list[int]) -> dict[int, int]:
    """Return dynsym_index -> current bucket, validating the existing chain table."""
    out: dict[int, int] = {}
    for bucket_index, head in enumerate(buckets):
        i = head
        seen: set[int] = set()
        while i:
            if i in seen:
                raise PrxHashError(f"cycle in .hash bucket {bucket_index} at symbol index {i}")
            if i >= len(chains):
                raise PrxHashError(f".hash bucket {bucket_index} points outside nchain: {i}")
            if i in out:
                raise PrxHashError(f"symbol index {i} is reachable from more than one bucket")
            seen.add(i)
            out[i] = bucket_index
            i = chains[i]
    return out


def rebuild_hash_from_symbol_buckets(nbucket: int, nchain: int, sym_to_bucket: dict[int, int]) -> tuple[list[int], list[int]]:
    buckets = [0] * nbucket
    chains = [0] * nchain

    # Deterministic order. Inserting at bucket head is the normal SysV style used
    # by linkers; lookup only depends on membership, not chain order.
    for sym_index in range(1, nchain):
        if sym_index not in sym_to_bucket:
            continue
        bucket = sym_to_bucket[sym_index]
        if not (0 <= bucket < nbucket):
            raise PrxHashError(f"bad bucket {bucket} for symbol index {sym_index}")
        chains[sym_index] = buckets[bucket]
        buckets[bucket] = sym_index
    return buckets, chains


def classify_symbol(sym: DynSym, groups: dict[tuple[int, int], ExportGroup]) -> tuple[str, ExportGroup | None, str | None]:
    parts = sym.prx_parts
    if not parts:
        return "regular", None, None
    nid, lib_ch, mod_ch = parts
    try:
        key = (id_num(lib_ch), id_num(mod_ch))
    except PrxHashError:
        return "unknown-prx", None, None
    group = groups.get(key)
    if not group:
        return "unknown-prx", None, None
    return "export", group, nid


def audit(data: bytes, path: Path, verbose: bool = False) -> AuditResult:
    elf = Elf64LE(data)
    hash_sh, nbucket, nchain, buckets, chains = elf.hash_table()
    syms = elf.dynsyms()
    groups = elf.export_groups()
    sym_to_bucket = buckets_to_symbol_bucket_map(buckets, chains)

    export_ok = export_bad = export_total = 0
    prx_non_export = regular_symbols = missing_bucket = 0
    bad_lines: list[str] = []

    for sym in syms[1:min(len(syms), nchain)]:
        kind, group, nid = classify_symbol(sym, groups)
        actual = sym_to_bucket.get(sym.index)
        if kind == "export" and group and nid:
            export_total += 1
            canonical = group.canonical(nid)
            expected = sysv_elf_hash(canonical) % nbucket
            if actual is None:
                missing_bucket += 1
                export_bad += 1
                bad_lines.append(
                    f"MISSING sym={sym.index} dynstr={sym.name} expected_bucket={expected} canonical={canonical}"
                )
            elif actual == expected:
                export_ok += 1
                if verbose:
                    bad_lines.append(
                        f"OK      sym={sym.index} dynstr={sym.name} bucket={actual} canonical={canonical}"
                    )
            else:
                export_bad += 1
                bad_lines.append(
                    f"BAD     sym={sym.index} dynstr={sym.name} actual_bucket={actual} expected_bucket={expected} canonical={canonical}"
                )
        elif kind == "unknown-prx":
            prx_non_export += 1
            if actual is None:
                missing_bucket += 1
        else:
            regular_symbols += 1
            if actual is None:
                missing_bucket += 1

    return AuditResult(
        path=path,
        nbucket=nbucket,
        nchain=nchain,
        hash_offset=hash_sh.offset,
        export_ok=export_ok,
        export_bad=export_bad,
        export_total=export_total,
        prx_non_export=prx_non_export,
        regular_symbols=regular_symbols,
        missing_bucket=missing_bucket,
        bad_lines=bad_lines,
    )


def fix_hash(data: bytes, *, unknown_policy: str = "preserve") -> tuple[bytes, list[str]]:
    """
    Rebuild .hash with correct buckets for known exported PRX symbols.

    unknown_policy:
        preserve - keep current buckets for non-export/import/regular dynsyms.
        dynstr   - hash unknown symbols from their literal .dynstr name. This is
                  useful for normal ELF files but NOT correct for observed SCE
                  import symbols, so it is opt-in only.
        drop     - omit unknown symbols from .hash chains.
    """
    work = bytearray(data)
    elf = Elf64LE(bytes(work))
    hash_sh, nbucket, nchain, buckets, chains = elf.hash_table()
    syms = elf.dynsyms()
    groups = elf.export_groups()
    if not groups:
        raise PrxHashError("no SCE export groups found in .dynamic; cannot compute PRX export canonical names")

    current = buckets_to_symbol_bucket_map(buckets, chains)
    desired: dict[int, int] = {}
    changed = 0
    export_seen = 0
    preserved = 0
    dynstr_unknown = 0
    dropped = 0
    reports: list[str] = []

    if len(syms) < nchain:
        raise PrxHashError(f".hash nchain={nchain} is larger than .dynsym count={len(syms)}")

    for sym in syms[1:nchain]:
        kind, group, nid = classify_symbol(sym, groups)
        if kind == "export" and group and nid:
            export_seen += 1
            canonical = group.canonical(nid)
            bucket = sysv_elf_hash(canonical) % nbucket
            old_bucket = current.get(sym.index)
            desired[sym.index] = bucket
            if old_bucket != bucket:
                changed += 1
                reports.append(
                    f"fix sym={sym.index}: {sym.name} bucket {old_bucket} -> {bucket}; canonical={canonical}"
                )
            continue

        if unknown_policy == "preserve":
            if sym.index not in current:
                raise PrxHashError(
                    f"cannot preserve non-export symbol {sym.index} ({sym.name!r}) because it is not reachable from current .hash; "
                    "use --unknown-policy dynstr or --unknown-policy drop only if you understand the risk"
                )
            desired[sym.index] = current[sym.index]
            preserved += 1
        elif unknown_policy == "dynstr":
            desired[sym.index] = sysv_elf_hash(sym.name) % nbucket
            dynstr_unknown += 1
        elif unknown_policy == "drop":
            dropped += 1
        else:
            raise PrxHashError(f"bad unknown policy: {unknown_policy}")

    if export_seen == 0:
        raise PrxHashError("no exported PRX symbols with known .dynamic export groups were found")

    new_buckets, new_chains = rebuild_hash_from_symbol_buckets(nbucket, nchain, desired)
    words = [nbucket, nchain] + new_buckets + new_chains
    struct.pack_into(f"<{len(words)}I", work, hash_sh.offset, *words)

    # Sanity-check all known exports after rebuilding.
    result = audit(bytes(work), Path("<patched>"), verbose=False)
    if result.export_bad:
        raise PrxHashError("internal sanity check failed after rebuilding .hash:\n" + "\n".join(result.bad_lines[:20]))

    reports.append(
        f"rebuilt .hash at file offset 0x{hash_sh.offset:x}; nbucket={nbucket}, nchain={nchain}; "
        f"exports={export_seen}, changed_exports={changed}, preserved_unknown={preserved}, "
        f"dynstr_unknown={dynstr_unknown}, dropped_unknown={dropped}"
    )
    return bytes(work), reports


def print_audit(result: AuditResult, *, quiet: bool = False, verbose: bool = False) -> None:
    if quiet:
        status = "OK" if result.ok else "BAD"
        print(f"{status}: {result.path}: exports {result.export_ok}/{result.export_total}, bad={result.export_bad}, missing={result.missing_bucket}")
        return

    print(f"{result.path}")
    print(f"  .hash: nbucket={result.nbucket}, nchain={result.nchain}, file_off=0x{result.hash_offset:x}")
    print(
        f"  exports: {result.export_ok}/{result.export_total} OK; "
        f"bad={result.export_bad}; non_export_prx={result.prx_non_export}; regular={result.regular_symbols}; missing_bucket={result.missing_bucket}"
    )
    if result.bad_lines:
        if verbose:
            for line in result.bad_lines:
                print("  " + line)
        else:
            for line in result.bad_lines[:20]:
                print("  " + line)
            if len(result.bad_lines) > 20:
                print(f"  ... {len(result.bad_lines) - 20} more lines; use --verbose")


def print_groups_and_symbols(data: bytes, path: Path) -> None:
    elf = Elf64LE(data)
    hash_sh, nbucket, nchain, buckets, chains = elf.hash_table()
    groups = elf.export_groups()
    current = buckets_to_symbol_bucket_map(buckets, chains)

    print(f"{path}")
    print(f".hash: nbucket={nbucket}, nchain={nchain}, file_off=0x{hash_sh.offset:x}")
    print("export groups:")
    if not groups:
        print("  <none>")
    else:
        for key in sorted(groups):
            g = groups[key]
            print(f"  {g.suffix} -> {g.library} / {g.module}")

    print("symbols:")
    print("index  kind         dynstr                 actual  expected  canonical")
    for sym in elf.dynsyms()[1:nchain]:
        kind, group, nid = classify_symbol(sym, groups)
        actual = current.get(sym.index)
        if kind == "export" and group and nid:
            canonical = group.canonical(nid)
            expected = sysv_elf_hash(canonical) % nbucket
            mark = "" if actual == expected else " !"
            print(f"{sym.index:5d}  export       {sym.name:21s} {str(actual):>6s} {expected:9d}{mark}  {canonical}")
        elif kind == "unknown-prx":
            print(f"{sym.index:5d}  non-export   {sym.name:21s} {str(actual):>6s} {'preserve':>9s}  <not recomputed>")
        else:
            print(f"{sym.index:5d}  regular      {sym.name:21s} {str(actual):>6s} {'preserve':>9s}  <not recomputed>")


def write_output(out_path: Path, data: bytes, *, overwrite: bool) -> None:
    if out_path.exists() and not overwrite:
        raise PrxHashError(f"output file exists: {out_path}; pass --overwrite")
    out_path.write_bytes(data)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Check/fix SCE PRX SysV .hash buckets for exported NID symbols."
    )
    ap.add_argument("input", help="input PRX/SPRX/ELF file")
    ap.add_argument("output", nargs="?", help="output file; omitted with --check/--list, or use --in-place")
    ap.add_argument("--check", action="store_true", help="only verify known exported PRX symbol buckets; exit 1 on mismatch")
    ap.add_argument("--list", action="store_true", help="print detected export groups and symbol bucket mapping")
    ap.add_argument("--in-place", action="store_true", help="patch the input file in place")
    ap.add_argument("--backup", action="store_true", help="with --in-place, create INPUT.bak before writing")
    ap.add_argument("--dry-run", action="store_true", help="show planned changes but do not write output")
    ap.add_argument("--overwrite", action="store_true", help="allow overwriting an existing output file")
    ap.add_argument("--quiet", action="store_true", help="short output")
    ap.add_argument("--verbose", action="store_true", help="verbose check/list output")
    ap.add_argument(
        "--unknown-policy",
        choices=("preserve", "dynstr", "drop"),
        default="preserve",
        help=(
            "how to handle non-export/import/regular symbols when rebuilding; "
            "default 'preserve' is safest for Sony PRX files"
        ),
    )
    args = ap.parse_args(argv)

    in_path = Path(args.input)
    data = in_path.read_bytes()

    if args.list:
        print_groups_and_symbols(data, in_path)
        return 0

    if args.check:
        result = audit(data, in_path, verbose=args.verbose)
        print_audit(result, quiet=args.quiet, verbose=args.verbose)
        return 0 if result.ok else 1

    if args.output and args.in_place:
        raise PrxHashError("use either an output path or --in-place, not both")
    if not args.output and not args.in_place and not args.dry_run:
        raise PrxHashError("output file is required unless --in-place, --dry-run, --check, or --list is used")

    patched, reports = fix_hash(data, unknown_policy=args.unknown_policy)
    if not args.quiet:
        for line in reports:
            print(line)

    if args.dry_run:
        if not args.quiet:
            print("dry-run: no file written")
        return 0

    if args.in_place:
        if args.backup:
            backup = in_path.with_name(in_path.name + ".bak")
            if backup.exists() and not args.overwrite:
                raise PrxHashError(f"backup file exists: {backup}; pass --overwrite")
            shutil.copy2(in_path, backup)
            if not args.quiet:
                print(f"backup: {backup}")
        in_path.write_bytes(patched)
        if not args.quiet:
            print(f"patched in place: {in_path}")
    else:
        out_path = Path(args.output)
        write_output(out_path, patched, overwrite=args.overwrite)
        if not args.quiet:
            print(f"wrote: {out_path} ({len(patched)} bytes)")

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except BrokenPipeError:
        raise SystemExit(1)
    except Exception as e:
        print(f"error: {e}", file=sys.stderr)
        raise SystemExit(1)
